name: flacardy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.22.1
  drift_flutter: ^0.1.0
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  flip_card: ^0.7.0
  loading_animation_widget: ^1.3.0
  confetti: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.22.0
  build_runner: ^2.4.13

flutter:
  assets: 
  - .env
  - assets/pocket.png
  uses-material-design: true
